// This file is auto-generated by Suprnova. Do not edit manually.
// Run `suprnova generate-types` to regenerate.

export interface AdminArticlesIndexProps {
  articles: Array<AdminArticleRow>;
}

export interface TagShowProps {
  tag: TaxonomyDetail;
}

export interface RegisterProps {
}

export interface TopicShowProps {
  topic: TaxonomyDetail;
}

export interface TopicsIndexProps {
  topics: Array<TaxonomyListItem>;
}

export interface MembersIndexProps {
  members: Array<MemberSummary>;
}

export interface AdminTaxonomyProps {
  categories: Array<AdminTaxonomyTermRow>;
  topics: Array<AdminTaxonomyTermRow>;
  tags: Array<AdminTagRow>;
  errors: Value;
}

export interface ForgotPasswordProps {
}

export interface CategoryShowProps {
  category: TaxonomyDetail;
}

export interface ArticleShowProps {
  article: ArticleDetail;
}

export interface ProfileProps {
  name: string;
  email: string;
  email_verified: boolean;
  profile: ProfileFormProps;
}

export interface LoginProps {
}

export interface HomeProps {
  headline: string;
  subheadline: string;
  features: Array<LandingFeature>;
  capabilities: Array<LandingCapability>;
  sample: LandingCodeSample;
}

export interface ArticlesIndexProps {
  articles: Array<ArticleSummary>;
}

export interface ResetPasswordProps {
  token: string;
}

export interface DashboardProps {
  user: UserInfo;
  cards: Array<DashboardCard>;
  actions: Array<DashboardAction>;
  account: AccountStatus;
}

export interface VerifyEmailProps {
  status: string | null;
}

export interface AdminArticleEditProps {
  article: ArticleFormState;
  errors: Value;
}

export interface MemberShowProps {
  member: MemberSummary;
}
export interface DocsPageProps {
  catalog: DocsCatalog;
  chapter: DocsChapter;
}
